### ISSUE TITLE
How do I fix sketchybar font?

### ISSUE THREAD

**Issue by SolsticeSpectrum** [Levvonci/dots#1]
I see question marks and isntead of emojis I see :safari: or :finder:

![image](https://github.com/user-attachments/assets/4fe6b0a3-166f-4c0f-860b-891a057a07d9)

**Comment by SolsticeSpectrum** [comment]
I installed sf-symbols and that fixed the icons but apps still show as `:safari:`
![image](https://github.com/user-attachments/assets/3649eed5-002e-4365-a03f-75308a444a7d)

**Comment by Levvonci** [comment]
> I installed sf-symbols and that fixed the icons but apps still show as `:safari:`
> 
> ![image](https://github.com/user-attachments/assets/3649eed5-002e-4365-a03f-75308a444a7d)
> 
> 

Are you using a nerd font?

**Comment by SolsticeSpectrum** [comment]
@Levvonci idk, probably? What fonts did you install?

**Comment by Levvonci** [comment]
> @Levvonci idk, probably? What fonts did you install?

Are you using one of these? https://www.nerdfonts.com/font-downloads

**Comment by Levvonci** [comment]
> > @Levvonci idk, probably? What fonts did you install?
> 
> Are you using one of these? https://www.nerdfonts.com/font-downloads

Currently using profont

**Comment by SolsticeSpectrum** [comment]
where do I get profont

**Comment by Levvonci** [comment]
> where do I get profont

From here:
https://www.nerdfonts.com/font-downloads
